---
output: html_document
---
<br>
*MACRO lab personnel in bold*  
<br>
**In review**  
<br>
Ashton, G.V., A. Freestone,…**B.S. Cheng**…, G.M. Ruiz (18th of 64 authors). Predator control of marine communities increases with temperature across 115 degrees of latitude.   

**Villeneuve, A.**, L.M. Komoroske, **B.S. Cheng**. Diminished warming tolerance and plasticity in low latitude populations of a marine gastropod.  

<br>

**Published**    
<br>
Hollarsmith, J.A., J.S. Sadowski, M.M.M. Picard, **B.S. Cheng**, J. Farlin, A. Russell, E.D. Grosholz. (2020) Effects of seasonal upwelling and runoff on water chemistry and growth and survival of native and commercial oysters. [Limnology and Oceanography](https://aslopubs.onlinelibrary.wiley.com/doi/abs/10.1002/lno.11293) 65:224-235  

Banerjee, S.M., C.D. Allen, T. Schmitt, **B.S. Cheng**, J.A. Seminoff, T. Eguchi, L.M. Komoroske. (2019) Baseline health parameters of eastern Pacific green turtles at Southern California foraging grounds. [Chelonian Conservation and Biology](https://www.chelonianjournals.org/doi/full/10.2744/CCB-1347.1) 18:163-174  

**Cheng, B.S.**, A.H. Altieri, M.E. Torchin, G.M. Ruiz (2019) Can marine reserves restore lost ecosystem function? A global synthesis. [Ecology](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.2617) 100:e02617 * Highlighted in Nature Sustainability   

**Cheng, B.S.**, G.M. Ruiz, A.H. Altieri, M.E. Torchin. (2019) The biogeography of invasion in tropical and temperate seagrass beds: testing interactive effects of predation and propagule pressure. [Diversity and Distributions](https://onlinelibrary.wiley.com/doi/10.1111/ddi.12850) 25:285-297

Bible, J.M., **B.S. Cheng**, A.L. Chang, M.C. Ferner, K. Wasson, C.J. Zabin, M. Latta, E. Sanford, A. Deck, E.D. Grosholz (2017) Timing of stressors alters interactive effects on a coastal foundation species. [Ecology](http://onlinelibrary.wiley.com/doi/10.1002/ecy.1943/full) 98:2468-2478

**Cheng, B.S.**, L.M. Komoroske, E.D. Grosholz (2017) Trophic sensitivity of invasive predator and native prey interactions: integrating environmental context and climate change. [Functional Ecology](http://onlinelibrary.wiley.com/wol1/doi/10.1111/1365-2435.12759/full) 31:642-652  
* [Capital Public Radio NPR](http://www.capradio.org/83061) | [Seeker Discovery News](http://www.seeker.com/climate-change-may-help-oysters-and-their-enemies-2040520387.html) | [Grist](https://grist.org/briefly/west-coast-oysters-are-getting-drilled-by-warmer-oceans/)  

**Cheng, B.S.**, A.L. Chang, A. Deck, M.C. Ferner (2016) Atmospheric rivers and the mass mortality of wild oysters: insight into an extreme future? [Proceedings of the Royal Society B](http://rspb.royalsocietypublishing.org/content/283/1844/20161462) 283:20161462 

Southern California Public Radio NPR | LA Times | Science News | Motherboard VICE | Marin Independent Journal  +cartoon! | International Business Times | National Resources Defense Council

**Cheng, B.S.** and E.D. Grosholz (2016) Environmental stress mediates trophic cascade strength and resistance to invasion. [Ecosphere](http://onlinelibrary.wiley.com/doi/10.1002/ecs2.1247/full) 7 (4): e01247. 10.1002/ecs2.1247  

**Cheng, B.S.**, J.M. Bible, A.L. Chang, M.C. Ferner, K. Wasson, C.J. Zabin, M. Latta, A. Deck, A.E. Todgham, E.D. Grosholz (2015) Testing local and global stressor impacts on a coastal foundation species using an ecologically realistic framework. [Global Change Biology](http://onlinelibrary.wiley.com/doi/10.1111/gcb.12895/abstract?campaign=wolacceptedarticle) 21:2488-2499  

Williams, S.L., N. Janetski, S. Blankenhorn, J. Abbott, **B.S. Cheng**, E. Crafton, D. Trockel (2014)
Ornamental marine species culture in the coral triangle: seahorse demonstration project in the Spermonde Islands, Sulawesi, Indonesia. [Environmental Management](http://link.springer.com/article/10.1007%2Fs00267-014-0343-6) 54:1342-1355  

Komoroske, L.M., R. Connon, J. Lindberg, **B.S. Cheng**, G. Castillo, M. Hasenbein, N. Fangue (2014)
Ontogeny influences sensitivity to climate change stressors in an endangered fish. [Conservation Physiology](http://conphys.oxfordjournals.org/content/2/1/cou008.abstract) 2:cou008-cou008

Kimbro, D.L., **B.S. Cheng**, E.D. Grosholz (2013) Biotic resistance in marine environments. [Ecology Letters](http://onlinelibrary.wiley.com/doi/10.1111/ele.12106/abstract) 16:821-833

Woodson, C.B., J.A. Barth, O.M. Cheriton, M.A. McManus, J.P. Ryan, L. Washburn, K.N. Carden, **B.S. Cheng**, J. Fernandes, L.E. Garske, T.C. Gouhier, A.J. Haupt, K.T. Honey, M.F. Hubbard,   A. Iles, L. Kara, M.C. Lynch, B. Mahoney, M. Pfaff, M.L. Pinsky, M.J. Robart, J.S. Stewart, S.J. Teck, A. True (2011) Observations of internal wave packets propagating along-shelf in northern Monterey Bay. [Geophysical Research Letters](http://onlinelibrary.wiley.com/doi/10.1029/2010GL045453/abstract) 38: L01605

**Cheng, B.S.** and K.A. Hovel (2010) Biotic resistance to invasion along an estuarine gradient. [Oecologia](http://link.springer.com/article/10.1007/s00442-010-1700-7) 164:1049-1059  
<br>

**Reports**  

Wasson, K., C. Zabin, J. Bible, E. Ceballos, A. Chang, **B.S. Cheng**,  A. Deck, E.D. Grosholz, M. Latta, M. Ferner. (2014) [A Guide to Olympia Oyster Restoration and Conservation](http://www.sfbaysubtidal.org/oysters_and_climate-about.html) 46 pp.

**Cheng, B.S.** and E. Gaskin, editors. (2011) Climate Impacts to the Nearshore Marine Environment and Coastal Communities: American Samoa and Fagatele Bay National Marine Sanctuary. [Marine Sanctuaries Conservation Series](http://sanctuaries.noaa.gov/science/conservation/fbnms_climate.html) ONMS-11-05. U.S. Department of Commerce, NOAA, Office of National Marine Sanctuaries, Silver Spring, MD. 71 pp. 

Largier, J.L, **B.S. Cheng**, and K.D. Higgason, editors. (2010) Climate Change Impacts: Gulf of the Farallones and Cordell Bank National Marine Sanctuaries. Report of a Joint Working Group of the Gulf of the Farallones and Cordell Bank National Marine Sanctuaries Advisory Councils. [Marine Sanctuaries Conservation Series](https://sanctuaries.noaa.gov/science/conservation/fb_cbnms_climate.html) ONMS-11-04.  U.S. Department of Commerce, NOAA, Office of National Marine Sanctuaries, Silver Spring, MD. 121 pp.